---
- name: Install SQL
  hosts: 192.168.1.81

  tasks:
 # - name: terraform SQL server
 #   terraform:
 #     project_path: '~/scripts/lab/sql/terraform/'
 #     lock: true
 #     state: present
  
  - name: load vars
    include_vars:
      file: '{{inventory_hostname}}.yaml'
      name: SQLInstall

 # - name: map source network share
 #   win_mapped_drive:
 #     letter: '{{SQLInstall.SourceDrive}}'
 #     path: '{{SQLInstall.SourceShare}}'
 #     username: '{{SQLInstall.SourceUsername}}'
 #     password: '{{SQLInstall.SourcePW}}'
      
  - name: mount SQL ISO
    win_disk_image:
      image_path: '\\192.168.1.23\Source\Microsoft\en_sql_server_2019_enterprise_x64_dvd_5e1ecc6b.iso'
      state: present
    register: disk_image_out
