---
- name: Install SQL
  hosts: 192.168.1.201
  become: true

  tasks:
  - name: terraform SQL server
    terraform:
      project_path: '~/scripts/lab/sql/terraform/'
      lock: true
      state: present
  
  - name: load vars
    includ_vars:
      file: '{{inventory_hostname}}.yaml'
      name: SQLInstall

  - name: map source network share
    win_mapped_drive:
      letter: '{{SQLInstall.SourceDrive}}'
      path: '{{SQLInstall.SourceShare}}'
      username: '{{SQLInstall.SourceUsername}}'
      password: '{{SQLInstall.SourcePW}}'
      
  - name: mount SQL ISO
    win_disk_image:
      image_path: '{{SQLInstall.SourceDrive}}\{{SQLInstall.SQLISOPath}}'
      state: present

